import type {
  AchievementDefinition,
  GameState,
  MilestoneDefinition,
  StoryEventDefinition,
  UpgradeDefinition,
} from './types';

export const SAVE_KEY = 'idle-cat-cafe.save.v2';
export const AUTO_SAVE_MS = 15_000;
export const OFFLINE_CAP_MS = 2 * 60 * 60 * 1000;
export const WIN_TARGET_REVENUE = 120_000;
export const WIN_TARGET_POPULARITY = 120;
export const MAX_LOGS = 10;
export const PRESTIGE_UNLOCK_REVENUE = 45_000;
export const STORY_EVENT_INTERVAL_MS = 42_000;

export const UPGRADE_DEFINITIONS: UpgradeDefinition[] = [
  {
    id: 'feather-toy',
    name: '逗猫羽毛棒',
    description: '优化招待动作，单次招待收益 +1。',
    basePrice: 12,
    priceScale: 1.5,
    effectType: 'click',
    effectValue: 1,
    branch: 'core',
  },
  {
    id: 'junior-clerk',
    name: '见习猫店员',
    description: '帮你接待散客，自动收益 +0.5 / 秒。',
    basePrice: 24,
    priceScale: 1.58,
    effectType: 'passive',
    effectValue: 0.5,
    branch: 'core',
  },
  {
    id: 'paw-sign',
    name: '猫爪招牌',
    description: '招牌更显眼，单次招待收益 +4。',
    basePrice: 70,
    priceScale: 1.66,
    effectType: 'click',
    effectValue: 4,
    unlockRevenue: 80,
    branch: 'core',
  },
  {
    id: 'senior-clerk',
    name: '资深猫店员',
    description: '会主动推荐甜点，自动收益 +2.6 / 秒。',
    basePrice: 180,
    priceScale: 1.71,
    effectType: 'passive',
    effectValue: 2.6,
    unlockRevenue: 260,
    branch: 'core',
  },
  {
    id: 'sofa-zone',
    name: '舒适沙发区',
    description: '客人更愿意久坐晒猫，全局收益 x1.14。',
    basePrice: 220,
    priceScale: 2.08,
    effectType: 'multiplier',
    effectValue: 1.14,
    maxLevel: 6,
    unlockRevenue: 420,
    branch: 'core',
  },
  {
    id: 'double-coffee',
    name: '双头咖啡机',
    description: '高峰期不断杯，自动收益 +10 / 秒。',
    basePrice: 520,
    priceScale: 1.82,
    effectType: 'passive',
    effectValue: 10,
    unlockRevenue: 1_000,
    branch: 'core',
  },
  {
    id: 'photo-wall',
    name: '橱窗打卡墙',
    description: '路人会停下拍照，全局收益 x1.28。',
    basePrice: 1_200,
    priceScale: 2.42,
    effectType: 'multiplier',
    effectValue: 1.28,
    maxLevel: 4,
    unlockRevenue: 2_400,
    branch: 'photo',
  },
  {
    id: 'theme-event',
    name: '猫咪主题活动',
    description: '限定活动让人气 +10，全局收益 x1.42。',
    basePrice: 2_400,
    priceScale: 2.9,
    effectType: 'combo',
    effectValue: 1.42,
    popularityBonus: 10,
    maxLevel: 4,
    unlockRevenue: 4_200,
    branch: 'event',
  },
  {
    id: 'bean-roaster',
    name: '冷萃烘豆线',
    description: '精品豆线稳定出杯，自动收益 +26 / 秒。',
    basePrice: 5_400,
    priceScale: 1.95,
    effectType: 'passive',
    effectValue: 26,
    unlockRevenue: 8_500,
    unlockPopularity: 30,
    branch: 'drink',
  },
  {
    id: 'signature-latte',
    name: '招牌拉花套餐',
    description: '单次招待收益 +24，适合冲刺阶段。',
    basePrice: 7_600,
    priceScale: 2.05,
    effectType: 'click',
    effectValue: 24,
    unlockRevenue: 12_000,
    unlockPopularity: 40,
    branch: 'drink',
  },
  {
    id: 'photo-booth',
    name: '猫咪摄影棚',
    description: '内容传播扩散，全局收益 x1.42。',
    basePrice: 14_000,
    priceScale: 2.75,
    effectType: 'multiplier',
    effectValue: 1.42,
    maxLevel: 3,
    unlockRevenue: 18_000,
    unlockPopularity: 55,
    branch: 'photo',
  },
  {
    id: 'influencer-night',
    name: '网红探店夜',
    description: '大型探店活动：人气 +15，全局收益 x1.58。',
    basePrice: 24_000,
    priceScale: 3.2,
    effectType: 'combo',
    effectValue: 1.58,
    popularityBonus: 15,
    maxLevel: 2,
    unlockRevenue: 30_000,
    unlockPopularity: 70,
    branch: 'photo',
  },
  {
    id: 'seasonal-festival',
    name: '节日主题周',
    description: '主题周带来大量客流，自动收益 +120 / 秒。',
    basePrice: 42_000,
    priceScale: 2.3,
    effectType: 'passive',
    effectValue: 120,
    unlockRevenue: 40_000,
    unlockPopularity: 85,
    branch: 'event',
  },
  {
    id: 'city-popup-tour',
    name: '城市巡回快闪',
    description: '品牌外扩让全局收益 x1.82。',
    basePrice: 78_000,
    priceScale: 3.6,
    effectType: 'multiplier',
    effectValue: 1.82,
    maxLevel: 2,
    unlockRevenue: 60_000,
    unlockPopularity: 100,
    unlockBrand: 2,
    branch: 'event',
  },
];

export const MILESTONES: MilestoneDefinition[] = [
  {
    id: 'street-cats',
    lifetimeRevenue: 30,
    popularityReward: 4,
    headline: '巷口熟客',
    message: '第一批常客开始专门绕路来摸猫，招待节奏终于稳定。',
  },
  {
    id: 'study-corner',
    lifetimeRevenue: 120,
    popularityReward: 6,
    headline: '作业圣地',
    message: '附近学生把你家当作临时学习点，晚间上座率明显提升。',
  },
  {
    id: 'community-star',
    lifetimeRevenue: 450,
    popularityReward: 8,
    headline: '社区明星店',
    message: '社区群里频繁推荐你的猫咪和奶咖，客流从断续变成稳定。',
  },
  {
    id: 'social-hotspot',
    lifetimeRevenue: 1_500,
    popularityReward: 12,
    headline: '打卡热店',
    message: '社交平台开始出现探店帖，周末会出现短暂排队。',
  },
  {
    id: 'city-list',
    lifetimeRevenue: 5_000,
    popularityReward: 16,
    headline: '榜单候选',
    message: '本地探店榜将你列为候选，品牌感开始成型。',
  },
  {
    id: 'regional-fame',
    lifetimeRevenue: 15_000,
    popularityReward: 20,
    headline: '区域热门',
    message: '隔壁商圈也有人专程过来，客群不再局限在附近街区。',
  },
  {
    id: 'city-spotlight',
    lifetimeRevenue: 35_000,
    popularityReward: 24,
    headline: '城市聚光',
    message: '媒体探店开始联系合作，你的猫咖进入“全城可见”阶段。',
  },
];

export const ACHIEVEMENTS: AchievementDefinition[] = [
  {
    id: 'click-200',
    name: '手速营业',
    description: '累计手动招待 200 次。',
    conditionType: 'clicks',
    target: 200,
  },
  {
    id: 'revenue-10k',
    name: '万鱼干店主',
    description: '单局累计营收达到 10,000。',
    conditionType: 'revenue',
    target: 10_000,
  },
  {
    id: 'popularity-80',
    name: '全城熟脸',
    description: '单局人气达到 80。',
    conditionType: 'popularity',
    target: 80,
  },
  {
    id: 'branch-drink',
    name: '饮品线成型',
    description: '把“冷萃烘豆线”升到 5 级。',
    conditionType: 'upgrade-level',
    target: 5,
    upgradeId: 'bean-roaster',
  },
  {
    id: 'branch-photo',
    name: '内容化运营',
    description: '把“猫咪摄影棚”升到 2 级。',
    conditionType: 'upgrade-level',
    target: 2,
    upgradeId: 'photo-booth',
  },
  {
    id: 'brand-5',
    name: '品牌经营者',
    description: '累计连锁品牌值达到 5。',
    conditionType: 'brand',
    target: 5,
  },
  {
    id: 'runs-3',
    name: '三周目店主',
    description: '完成 3 次品牌重整。',
    conditionType: 'runs',
    target: 3,
  },
];

export const STORY_EVENTS: StoryEventDefinition[] = [
  {
    id: 'afternoon-rush',
    headline: '午后高峰',
    message: '下午三点忽然涌进一波客人，吧台节奏明显加快。',
    minRevenue: 200,
  },
  {
    id: 'campus-group',
    headline: '校园社团来访',
    message: '一支校园社团把你列进每周固定活动点，客流更稳定了。',
    minRevenue: 1_500,
  },
  {
    id: 'influencer-drop',
    headline: '网红探店',
    message: '本地博主发布探店视频，门口出现拍照排队。',
    minRevenue: 8_000,
    minPopularity: 35,
  },
  {
    id: 'festival-week',
    headline: '节日主题周',
    message: '你推出节日限定菜单，节庆客流带来一轮冲刺。',
    minRevenue: 20_000,
    minPopularity: 60,
  },
  {
    id: 'brand-collab',
    headline: '联名邀请',
    message: '品牌方发来联名邀约，你的小店已经具备外扩势能。',
    minRevenue: 55_000,
    minBrand: 1,
  },
];

export function createInitialGameState(now: number): GameState {
  const upgrades = Object.fromEntries(UPGRADE_DEFINITIONS.map((upgrade) => [upgrade.id, 0]));
  const upgradeIncome = Object.fromEntries(
    UPGRADE_DEFINITIONS.map((upgrade) => [upgrade.id, 0]),
  );

  return {
    fish: 0,
    lifetimeRevenue: 0,
    popularity: 0,
    globalMultiplier: 1,
    upgrades,
    lastSavedAt: now,
    hasWon: false,
    claimedMilestones: [],
    logs: [],
    buyMode: 1,
    brandValue: 0,
    runs: 0,
    bestRunRevenue: 0,
    soundEnabled: true,
    claimedAchievements: [],
    stats: {
      totalClicks: 0,
      totalOfflineIncome: 0,
      lifetimeClickIncome: 0,
      lifetimePassiveIncome: 0,
      upgradeIncome,
    },
  };
}
